export const FETCH_TODOS = 'FETCH_TODOS'
export const NEW_TODO = 'NEW_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const UPDATE_TODO = 'UPDATE_TODO'

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
export const NEW_CATEGORY = 'NEW_CATEGORY'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'

export const NEW_RELATION = 'NEW_RELATION'

export const FETCH_TODOS_BY_CATEGORY = 'FETCH_TODOS_BY_CATEGORY'